[build]
  command = "NODE_OPTIONS=--openssl-legacy-provider
npm run build npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "/scripts/zulip-notification"
